<%@ Page Title="Address" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Address.aspx.cs" Inherits="berkeley.WebForm4" %>
<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">

    <div class="row">
        <div class="col d-flex nucleo text-sm">
            <div class="card flex-fill p-4 ">
                

                <div class="mb-2 text-center">
                    <h5><asp:Label ID="Label1"  runat="server" Text="Address Details"></asp:Label></h5>
                    <hr />
                </div>

                <div class="row form-label">

                    <div class ="col-5">
                     <asp:Label ID="Label3" class="label" runat="server" for="TextBoxAuthor" Text="Country * : "></asp:Label>
                    <div class ="mt-2">
                    <asp:TextBox class="form-control" ID="AddCountryTB" runat="server" MaxLength="50" placeholder="Country Name" required="true"></asp:TextBox> 
                        </div>
                    </div>

                   <div class ="col-5 mx-auto">
                     <asp:Label ID="Label6" class="label" runat="server" for="TextBoxAuthor" Text="City : "></asp:Label>
                    <div class ="mt-2">
                    <asp:TextBox class="form-control" ID="AddCityTB" runat="server" placeholder="City Name" MaxLength="50" required="true"></asp:TextBox> 
                        </div>
                    </div>

                   <div class ="col-5 mt-4">
                     <asp:Label ID="Label7" class="label" runat="server" for="TextBoxAuthor" Text="Zip Code: "></asp:Label>
                    <div class ="mt-2">
                    <asp:TextBox class="form-control" ID="AddZipTB" runat="server" placeholder="Zip Code" MaxLength="10" required="true"></asp:TextBox> 
                        </div>
                    </div>
                              
                </div>
             
                
                <div>
                    <asp:TextBox ID="AddID" runat="server" Visible ="false"></asp:TextBox>
                </div>
                

                <div class="mt-4 text-end">
                    <asp:Button ID="ButtonSubmit" runat="server" Text="Submit" class="btn btn-primary btn-lg  font-small" OnClick="ButtonSubmit_Click"/>
                </div>
            
            </div>
        </div>
    </div>
    
    <div class="row mt-4">
        <div class="col d-flex">
            <div class="card flex-fill p-4 shadow">

                <div class="">
                    
                    <asp:GridView   ID="AddressGridView" runat="server" DataKeyNames="House_ID" 
                                    OnRowDataBound="OnRowDataBound" 
                                    OnRowEditing="OnRowEditing" 
                                    OnRowCancelingEdit="OnRowCancelingEdit"  
                                    OnRowDeleting="OnRowDeleting" 
                                    EmptyDataText="No records has been added." 
                                    AutoGenerateEditButton="True" 
                                    AutoGenerateDeleteButton="True"
                                    class="table table-hover table-responsive text-sm border border-light" >

                    </asp:GridView>


                </div>
            
            </div>
        </div>
    </div>
    
</asp:Content>
