<%@ Page Title="Module" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Module.aspx.cs" Inherits="berkeley.WebForm1" %>


<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">

    <div class="row">
        <div class="col d-flex nucleo text-sm">
            <div class="card flex-fill p-4 ">
                

                <div class="mb-2 text-center">
                    <h5><asp:Label ID="Label1"  runat="server" Text="Module Details"></asp:Label></h5>
                    <hr />
                </div>

                <div class="row form-label">

                   <div class ="col-5">
                     <asp:Label ID="Label3" class="label" runat="server" for="TextBoxAuthor" Text="Module Name * : "></asp:Label>
                    <div class ="mt-2">
                    <asp:TextBox class="form-control" ID="ModNameTB" runat="server" MaxLength="100" placeholder="Module Name" required="true"></asp:TextBox> 
                        </div>
                    </div>

              

                   <div class ="col-5 mx-auto">
                     <asp:Label ID="Label6" class="label" runat="server" for="TextBoxAuthor" Text="Module Credit* : "></asp:Label>
                    <div class ="mt-2">
                    <asp:TextBox class="form-control" ID="ModCreditTB" runat="server" placeholder="Module Credit" MaxLength="9" pattern="[0-9]*" required="true"></asp:TextBox> 
                        </div>
                    </div>

                    
                  </div>
             
                
                <div>
                    <asp:TextBox ID="ModID" runat="server" Visible ="false"></asp:TextBox>
                </div>
                

                <div class="mt-4 text-end">
                    <asp:Button ID="ButtonSubmit" runat="server" Text="Submit" class="btn btn-primary btn-lg  font-small" OnClick="ButtonSubmit_Click"/>
                </div>
            
            </div>
        </div>
    </div>
    
    <div class="row mt-4">
        <div class="col d-flex">
            <div class="card flex-fill p-4 shadow">

                <div class="">
                    
                    <asp:GridView   ID="ModuleGridView" runat="server" DataKeyNames="Module_ID" 
                                    OnRowDataBound="OnRowDataBound" 
                                    OnRowEditing="OnRowEditing" 
                                    OnRowCancelingEdit="OnRowCancelingEdit"  
                                    OnRowDeleting="OnRowDeleting" 
                                    EmptyDataText="No records has been added." 
                                    AutoGenerateEditButton="True" 
                                    AutoGenerateDeleteButton="True"
                                    class="table table-hover table-responsive text-sm border border-light" >
                                    
                                    

                    </asp:GridView>


                </div>
            
            </div>
        </div>
    </div>
    
</asp:Content>
